### PR TITLE
Additional data for Slovakia scraper

### PR DESCRIPTION
**Pull request by redoper1**
Added additional available data from the source.

### CODE REVIEW

**Comment by redoper1** [comment]
I have added .gitignore to ignore `node_modules` and `apify_storage` folders for the scraper, but that rules would be maybe better to be added to the root .gitignore.

Then I have added webhook for email notifications when scraping fails and fixed the data check against the latest data.

**Comment by remyoucef** [comment]
Thanks, we will take it into consideration.

I advise you to follow this guide https://gitlab.com/apify-public/wiki/-/wikis/Public-actors/How-to-add-a-new-Covid-19-Actor

**Comment by redoper1** [comment]
This scraper had previously all this data before it has been moved into this merged repository and rewritten to BasicActor by laster04 to resolve https://github.com/apifytech/covid-19/issues/23, so I don't see a point in adding a new scraper.

**Comment by remyoucef** [comment]
Yes, I'm aware of that. I mean the maintenance part of the guide.
https://gitlab.com/apify-public/wiki/-/wikis/Public-actors/How-to-add-a-new-Covid-19-Actor#maintenance

**Comment by remyoucef** [comment]
Generally, we create issues before fixing them so they don't get fixed by many developers at the same time.

**Comment by redoper1** [comment]
> Generally, we create issues before fixing them so they don't get fixed by many developers at the same time.

Yeah, I see now. Sorry, it wasn't there when I read that documentation previously.
So should I create a new issue or it will be sufficient to add mention to that already existing one about that scraper (linked above) in which you asked if it can be closed?

**Comment by remyoucef** [comment]
Yes, we're going to make the process clear.
No need for an issue to this, the maintainers will check the PR.
Thanks!

**Comment by redoper1** [comment]
Ok, thank you very much. Next time I will do it properly 🙂

**Comment by remyoucef** [comment]
You're welcome! 👍

**Pull request merged**
